dataset:
  background: ./pytest_temp/pipeline_test/2021_06_11_recOrder_pytest_20x_04NA/BG
  background_ROI: null
  calibration_metadata: ./pytest_temp/pipeline_test/2021_06_11_recOrder_pytest_20x_04NA/calib_metadata.txt
  data_dir: ./
  data_save_name: ''
  data_type: ometiff
  method: QLIPP
  mode: 3D
  positions:
  - 1
  save_dir: ./
  timepoints:
  - 0
post_processing:
  denoise:
    channels:
    - Retardance
    level:
    - 1
    threshold:
    - 5
    use: false
  registration:
    channel_idx:
    - 1
    shift:
    - - 0
      - -100
      - -100
    use: false
pre_processing:
  denoise:
    channels:
    - S0
    - S1
    - S2
    - S3
    level:
    - 1
    - 1
    - 1
    - 1
    threshold:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    use: true
processing:
  NA_condenser: 0.4
  NA_objective: 1.2
  TV_reg_abs_2D: 0.0001
  TV_reg_ph_2D: 0.0001
  TV_reg_ph_3D: 5.0e-05
  Tik_reg_abs_2D: 0.0001
  Tik_reg_ph_2D: 0.0001
  Tik_reg_ph_3D: 0.0001
  background_correction: local_fit
  focus_zidx: null
  gpu_id: 0
  itr_2D: 50
  itr_3D: 50
  magnification: 63
  n_objective_media: 1.33
  output_channels:
  - S0
  - S1
  - S2
  - S3
  - Retardance
  - DAPI
  pad_z: 0
  phase_denoiser_2D: Tikhonov
  phase_denoiser_3D: Tikhonov
  pixel_size: 6.5
  qlipp_birefringence_only: true
  rho_2D: 1
  rho_3D: 0.001
  use_gpu: false
  wavelength: 532
  z_step: null
