dataset:
  background: '/gpfs/CompMicro/rawdata/hummingbird/Cameron/2021_05_10_NewKazansky_63x_WI_04NA/BG'

  #(str or list) Background folder(s) within the experiment folder
  ##   a list, e.g. ['/path/to/bg_1', '/path/to/bg_2'], of one background dataset per sample

  calibration_metadata: '/gpfs/CompMicro/rawdata/hummingbird/Cameron/2021_05_10_NewKazansky_63x_WI_04NA/metadata.txt'

processing:
  output_channels: ['Retardance', 'Orientation','Brightfield', 'Phase3D']

  # (list) Any combination of the following values.
  #    'Retardance', 'Orientation','Brightfield', 'Phase3D'
  #     order of the channels specifies the order in which they will be written

  #    can also specify custom names of fluorescence channels 'GFP' or 'DAPI' or 'Nuclei'.
  #    The order in which fluor channels are listed corresponds to their order in
  #    the acquisition.  Specified name stored in the metadata.

  use_gpu: False
  # (bool) Option to use GPU processing if True (require cupy to be installed)

  gpu_id: 0
  # (int) ID of GPU to be used

  ########################################
  #    PHASE RECONSTRUCTION PARAMETERS   #
  ########################################

  wavelength: 532
  # (int) wavelength of the illumination in nm

  pixel_size: 6.5
  # (float) Camera pixel size in the unit of um

  magnification: 63
  # (float) Magnification of the objective

  NA_objective: 1.2
  # (float) Numerical aperture of the objective

  NA_condenser: 0.4
  # (float) Numerical aperture of the condenser

  n_objective_media: 1.33
  # (float) Refractive index of the objective immersion oil

  z_step: 0.25
  # (int) Step size of the z-dimension in um

  pad_z: 0
  # (int) Number of z slices padded above and below the dataset for 3D phase reconstruction to avoid boundary artifacts

  ## Denoiser parameters ##