default: 'QLIPP_3D'
# the default configratuons for 3D Reconstruction, 3D Reconstruction over time, and 2D reconstruction over time

dataset:
  data_dir: '/gpfs/CompMicro/Spinningdisk/RawData/virtualstaining/2019_02_15_kidney_slice'
  # (str) The path of the folder that holds raw data

  samples: ['Tissue_Section_1']
  # (str or list) Acquisition folder(s) within the experiment folder to process,

  positions: 'all'
  # (str or list) Positions within all of sample folders that are to be analyzed.
  ##   'all'
  ##   [0, N] for pos 0 through N

  timepoints: 'all'
  # (str, list, or range) Timepoints to be analyzed.
  # The same set of timepoints will be analyzed for all positions and z-slices within a given sample
  # If the data do not contain z slices, leave out this parameter or set to 'all'
  ##   'all'
  ##   [0, 10, 20]
  ##   !!python/object/apply:builtins.range [10, 50, 5], in which case timepoints in range(10,50,5) will be analyzed
  ##   [['all'], [0, 10, 20]], in which case all timepoints from Sample1 and timepoints 0, 10, and 20 from Sample2 will be analyzed

  background: '/gpfs/CompMicro/Spinningdisk/RawData/virtualstaining/2019_02_15_kidney_slice/BG'

  #(str or list) Background folder(s) within the experiment folder
  ##   a list, e.g. ['/path/to/bg_1', '/path/to/bg_2'], of one background dataset per sample

  background_ROI:

  calibration_metadata: '/gpfs/CompMicro/Spinningdisk/RawData/virtualstaining/2019_02_15_kidney_slice/metadata.txt'

  processed_dir: '/gpfs/CompMicro/Projects/reconOrderTestData'
  # (str) The path of the parent folder where the output will be saved

processing:
  output_channels: ['Retardance', 'Orientation','Brightfield', 'Phase3D']

  # (list) Any combination of the following values.
  #    'Retardance', 'Orientation','Brightfield', 'Phase3D'
  #     order of the channels specifies the order in which they will be written

  #    can also specify custom names of fluorescence channels 'GFP' or 'DAPI' or 'Nuclei'.
  #    The order in which fluor channels are listed corresponds to their order in
  #    the acquisition.  Specified name stored in the metadata.

  background_correction: 'Local_fit'
  # (str) Background correction method, one of the following
  ##   'None': no background correction will be performed
  ##   'Global': standard background correction / normalization performed from given background data
  ##   'Local_filter': sample is first corrected with background provided in dataset section. The residual background is further estimated with a low-pass filter and removed.
  ##   'Local_fit': sample is first corrected with background provided in dataset section. The residual background is further estimated by a polynomial fit and removed. More robust than filtering approach.

  local_fit_order: 2
  # (int) order of the polynomial used for 'Local_fit' background correction

  flatfield_correction: False
  # (bool) perform flat-field correction on fluorescence images if True

  use_gpu: False
  # (bool) Option to use GPU processing if True (require cupy to be installed)

  gpu_id: 0
  # (int) ID of GPU to be used

  ########################################
  #    PHASE RECONSTRUCTION PARAMETERS   #
  ########################################

  wavelength: 532
  # (int) wavelength of the illumination in nm

  pixel_size: 6.5
  # (float) Camera pixel size in the unit of um

  magnification: 63
  # (float) Magnification of the objective

  NA_objective: 1.47
  # (float) Numerical aperture of the objective

  NA_condenser: 0.9
  # (float) Numerical aperture of the condenser

  n_objective_media: 1.512
  # (float) Refractive index of the objective immersion oil

  focus_zidx: 22
  # (int) Index of the focused z slice of the dataset for 2D phase reconstruction

  pad_z: 0
  # (int) Number of z slices padded above and below the dataset for 3D phase reconstruction to avoid boundary artifacts

  ## Denoiser parameters ##

  phase_denoiser_3D: 'Tikhonov'
  # (str) Options of denoiser for 3D phase reconstruction
  ##   'Tikhonov' or 'TV' (total variation)

  #### 3D Tikhonov parameters ####
  # if noise is higher raise an order of magnitude to see if the recon is better

  Tik_reg_ph_3D: 1.0e-4
  # (float) Tikhonov regularization parameter for 3D phase
  ##   1.0e-3 to 1.0e-4 should work generally when noise is low

  #### 3D TV parameters ####
  # For more noisy data, raise TV_reg to enforce stronger denoising effect

  rho_3D: 1.0e-3
  # (float) rho parameters in the 2D ADMM formulation
  ##   1.0e-3 is generally good, no need to tune

  itr_3D: 50
  # (int) Number of iterations for 3D TV denoiser
  ##   50 is generally good, no need to tune

  TV_reg_ph_3D: 5.0e-5
  # (float) TV regularization parameter for 3D phase
  ##   5.0e-5 is generally good